/**
* Project:  JusTeam/client
*
* Module name: Discover Component 2
*
* Author: ANTD Motion, ZAHNG Yuechen
*
* Date created: 20180329
*
* Purpose: The list of core functions in discover page (Generated by Antd Motion)
*
* Revision History:
*
* Date      Author          Ref    Revision
* 20180329  Julian          1      Edit description info.
*
**/
import React from 'react';
import QueueAnim from 'rc-queue-anim';
import TweenOne from 'rc-tween-one';
import OverPack from 'rc-scroll-anim/lib/ScrollOverPack';

class Content extends React.Component {
  static defaultProps = {
    className: 'content0',
  };

  render() {
    const props = { ...this.props };
    const isMode = props.isMode;
    delete props.isMode;
    const animType = {
      queue: isMode ? 'bottom' : 'right',
      one: isMode ? { y: '+=30', opacity: 0, type: 'from' }
        : { x: '-=30', opacity: 0, type: 'from' },
    }
    return (
      <div
        {...props}
        className={`content-template-wrapper content-half-wrapper ${props.className}-wrapper`}
      >
        <OverPack
          className={`content-template ${props.className}`}
          location={props.id}
        >
          <TweenOne
            key="img"
            animation={animType.one}
            className={`${props.className}-img`}
            id={`${props.id}-imgWrapper`}
            resetStyleBool
          >
            <span id={`${props.id}-img`}>
              <img width="100%" src="https://zos.alipayobjects.com/rmsportal/nLzbeGQLPyBJoli.png" />
            </span>
          </TweenOne>
          <QueueAnim
            className={`${props.className}-text`}
            type={animType.queue}
            key="text"
            leaveReverse
            ease={['easeOutCubic', 'easeInCubic']}
            id={`${props.id}-textWrapper`}
          >
            <h1 key="h1" id={`${props.id}-title`}>
              Create A Team
            </h1>
            <p key="p" id={`${props.id}-content`}>
              With JusTeam, people can find teammates by launching a team. Users need to type in some pre-requisite information such as the maximum number of teammates, the category of the activity and the title of the team the time they create a new team.
            </p>
          </QueueAnim>
        </OverPack>
      </div>
    );
  }
}


export default Content;
